spring:
  application:
    name: SpringLudotheque

  #Connection to DB
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=LUDO_BD;integratedSecurity=false;encrypt=false;trustServerCertificate=false
    username: LUDO_USER
    password: LUDO_PWD
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  #Options to DB
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create